/********************************************************************************
** Form generated from reading UI file 'widget.ui'
**
** Created by: Qt User Interface Compiler version 5.12.9
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WIDGET_H
#define UI_WIDGET_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QTreeWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Widget
{
public:
    QHBoxLayout *horizontalLayout;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QPushButton *btn_FoundHomework;
    QPushButton *btn_Valkyrie;
    QPushButton *btn_SetBoss;
    QPushButton *btn_SetHomework;
    QPushButton *icon2;
    QPushButton *icontext;
    QPushButton *btn_ResetHomework;
    QWidget *page_2;
    QLabel *label_3;
    QLineEdit *lineEdit_name;
    QLabel *label;
    QLabel *label_2;
    QPushButton *btn_ValkyrieIcon;
    QLineEdit *lineEdit_nickname;
    QPushButton *btn_ValkyrieOk;
    QPushButton *btn_ValkyrieCancel;
    QLabel *label_15;
    QPushButton *icon2_3;
    QWidget *page_3;
    QPushButton *btn_BossOk;
    QPushButton *btn_BossCancle;
    QLineEdit *lineEdit_name_B;
    QLineEdit *lineEdit_nickname_B;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QPushButton *btn_BossIcon;
    QLabel *label_14;
    QPushButton *icon2_2;
    QWidget *page_4;
    QTableWidget *tableWidget;
    QPushButton *btn_SelectBossCancle;
    QLabel *label_7;
    QPushButton *btn_SelectBossOk;
    QWidget *page_5;
    QPushButton *btn_H_BossIcon;
    QLineEdit *lineEdit_H_BossName;
    QLabel *label_8;
    QLineEdit *lineEdit_H_Score;
    QLabel *label_9;
    QPushButton *btn_H_CaptainIcon;
    QPushButton *btn_H_Valkyrie2Icon;
    QPushButton *btn_H_Valkyrie3Icon;
    QPushButton *btn_H_Cancle;
    QLabel *label_10;
    QPushButton *btn_H_Ok;
    QLabel *lineEdit_H_Captain;
    QLabel *lineEdit_H_Valkyrie2;
    QLabel *lineEdit_H_Valkyrie3;
    QLabel *label_13;
    QPushButton *icon2_4;
    QWidget *page_6;
    QTableWidget *tableWidget_2;
    QPushButton *btn_H_ValkyrieTavleWidgetCancle;
    QPushButton *btn_H_ValkyrieTableWidegtOk;
    QWidget *page_7;
    QPushButton *btn_H_upBoss;
    QPushButton *btn_H_2Boss;
    QPushButton *btn_H_3Boss;
    QPushButton *btn_HF_Cancle;
    QPushButton *btn_HF_Ok;
    QLabel *label_11;
    QLabel *label_upboss;
    QLabel *label_2boss;
    QLabel *label_3boss;
    QLabel *label_12;
    QTextEdit *textEdit;
    QPushButton *btn_HF_upBoss_1;
    QPushButton *btn_HF_upBoss_2;
    QPushButton *btn_HF_upBoss_3;
    QPushButton *btn_HF_2Boss_1;
    QPushButton *btn_HF_2Boss_3;
    QPushButton *btn_HF_2Boss_2;
    QPushButton *btn_HF_3Boss_1;
    QPushButton *btn_HF_3Boss_2;
    QPushButton *btn_HF_3Boss_3;
    QWidget *page_8;
    QTreeWidget *treeWidget;
    QPushButton *btn_RH_back;
    QPushButton *btn_RH_ok;
    QPushButton *btn_RH_delete;

    void setupUi(QWidget *Widget)
    {
        if (Widget->objectName().isEmpty())
            Widget->setObjectName(QString::fromUtf8("Widget"));
        Widget->setEnabled(true);
        Widget->resize(749, 524);
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(Widget->sizePolicy().hasHeightForWidth());
        Widget->setSizePolicy(sizePolicy);
        Widget->setMinimumSize(QSize(749, 524));
        Widget->setMaximumSize(QSize(749, 524));
        Widget->setBaseSize(QSize(749, 524));
        QFont font;
        font.setFamily(QString::fromUtf8("Adobe Devanagari"));
        Widget->setFont(font);
        Widget->setContextMenuPolicy(Qt::DefaultContextMenu);
        horizontalLayout = new QHBoxLayout(Widget);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        horizontalLayout->setSizeConstraint(QLayout::SetNoConstraint);
        stackedWidget = new QStackedWidget(Widget);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        btn_FoundHomework = new QPushButton(page);
        btn_FoundHomework->setObjectName(QString::fromUtf8("btn_FoundHomework"));
        btn_FoundHomework->setGeometry(QRect(10, 10, 91, 31));
        btn_Valkyrie = new QPushButton(page);
        btn_Valkyrie->setObjectName(QString::fromUtf8("btn_Valkyrie"));
        btn_Valkyrie->setGeometry(QRect(10, 90, 91, 31));
        btn_SetBoss = new QPushButton(page);
        btn_SetBoss->setObjectName(QString::fromUtf8("btn_SetBoss"));
        btn_SetBoss->setGeometry(QRect(10, 130, 91, 31));
        QFont font1;
        font1.setFamily(QString::fromUtf8("\345\256\213\344\275\223"));
        btn_SetBoss->setFont(font1);
        btn_SetHomework = new QPushButton(page);
        btn_SetHomework->setObjectName(QString::fromUtf8("btn_SetHomework"));
        btn_SetHomework->setGeometry(QRect(10, 50, 91, 31));
        icon2 = new QPushButton(page);
        icon2->setObjectName(QString::fromUtf8("icon2"));
        icon2->setGeometry(QRect(400, 10, 331, 501));
        icon2->setIconSize(QSize(306, 523));
        icontext = new QPushButton(page);
        icontext->setObjectName(QString::fromUtf8("icontext"));
        icontext->setGeometry(QRect(270, 330, 291, 191));
        icontext->setIconSize(QSize(200, 116));
        btn_ResetHomework = new QPushButton(page);
        btn_ResetHomework->setObjectName(QString::fromUtf8("btn_ResetHomework"));
        btn_ResetHomework->setGeometry(QRect(10, 170, 91, 31));
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        label_3 = new QLabel(page_2);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(70, 240, 91, 31));
        lineEdit_name = new QLineEdit(page_2);
        lineEdit_name->setObjectName(QString::fromUtf8("lineEdit_name"));
        lineEdit_name->setGeometry(QRect(180, 70, 91, 22));
        label = new QLabel(page_2);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(69, 70, 101, 31));
        label_2 = new QLabel(page_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(70, 150, 91, 31));
        btn_ValkyrieIcon = new QPushButton(page_2);
        btn_ValkyrieIcon->setObjectName(QString::fromUtf8("btn_ValkyrieIcon"));
        btn_ValkyrieIcon->setGeometry(QRect(180, 230, 100, 100));
        btn_ValkyrieIcon->setMinimumSize(QSize(100, 100));
        btn_ValkyrieIcon->setMaximumSize(QSize(100, 100));
        btn_ValkyrieIcon->setIconSize(QSize(100, 100));
        lineEdit_nickname = new QLineEdit(page_2);
        lineEdit_nickname->setObjectName(QString::fromUtf8("lineEdit_nickname"));
        lineEdit_nickname->setGeometry(QRect(180, 150, 91, 22));
        btn_ValkyrieOk = new QPushButton(page_2);
        btn_ValkyrieOk->setObjectName(QString::fromUtf8("btn_ValkyrieOk"));
        btn_ValkyrieOk->setGeometry(QRect(620, 450, 80, 22));
        btn_ValkyrieCancel = new QPushButton(page_2);
        btn_ValkyrieCancel->setObjectName(QString::fromUtf8("btn_ValkyrieCancel"));
        btn_ValkyrieCancel->setGeometry(QRect(490, 450, 80, 21));
        label_15 = new QLabel(page_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(20, 10, 111, 41));
        QFont font2;
        font2.setFamily(QString::fromUtf8("\345\256\213\344\275\223"));
        font2.setPointSize(15);
        label_15->setFont(font2);
        icon2_3 = new QPushButton(page_2);
        icon2_3->setObjectName(QString::fromUtf8("icon2_3"));
        icon2_3->setGeometry(QRect(400, 10, 331, 501));
        icon2_3->setIconSize(QSize(306, 523));
        stackedWidget->addWidget(page_2);
        icon2_3->raise();
        label_3->raise();
        lineEdit_name->raise();
        label->raise();
        label_2->raise();
        btn_ValkyrieIcon->raise();
        lineEdit_nickname->raise();
        btn_ValkyrieOk->raise();
        btn_ValkyrieCancel->raise();
        label_15->raise();
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        btn_BossOk = new QPushButton(page_3);
        btn_BossOk->setObjectName(QString::fromUtf8("btn_BossOk"));
        btn_BossOk->setGeometry(QRect(640, 469, 80, 21));
        btn_BossCancle = new QPushButton(page_3);
        btn_BossCancle->setObjectName(QString::fromUtf8("btn_BossCancle"));
        btn_BossCancle->setGeometry(QRect(550, 469, 80, 21));
        lineEdit_name_B = new QLineEdit(page_3);
        lineEdit_name_B->setObjectName(QString::fromUtf8("lineEdit_name_B"));
        lineEdit_name_B->setGeometry(QRect(180, 110, 113, 20));
        lineEdit_nickname_B = new QLineEdit(page_3);
        lineEdit_nickname_B->setObjectName(QString::fromUtf8("lineEdit_nickname_B"));
        lineEdit_nickname_B->setGeometry(QRect(180, 170, 113, 20));
        label_4 = new QLabel(page_3);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(73, 110, 81, 21));
        label_4->setFont(font1);
        label_5 = new QLabel(page_3);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(73, 170, 81, 21));
        label_5->setFont(font1);
        label_6 = new QLabel(page_3);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(73, 270, 81, 21));
        label_6->setFont(font1);
        btn_BossIcon = new QPushButton(page_3);
        btn_BossIcon->setObjectName(QString::fromUtf8("btn_BossIcon"));
        btn_BossIcon->setGeometry(QRect(180, 270, 256, 100));
        btn_BossIcon->setMinimumSize(QSize(256, 100));
        btn_BossIcon->setMaximumSize(QSize(256, 100));
        btn_BossIcon->setIconSize(QSize(256, 100));
        label_14 = new QLabel(page_3);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(50, 40, 101, 31));
        label_14->setFont(font2);
        icon2_2 = new QPushButton(page_3);
        icon2_2->setObjectName(QString::fromUtf8("icon2_2"));
        icon2_2->setGeometry(QRect(400, 10, 331, 501));
        icon2_2->setIconSize(QSize(306, 523));
        stackedWidget->addWidget(page_3);
        icon2_2->raise();
        btn_BossOk->raise();
        btn_BossCancle->raise();
        lineEdit_name_B->raise();
        lineEdit_nickname_B->raise();
        label_4->raise();
        label_5->raise();
        label_6->raise();
        btn_BossIcon->raise();
        label_14->raise();
        page_4 = new QWidget();
        page_4->setObjectName(QString::fromUtf8("page_4"));
        tableWidget = new QTableWidget(page_4);
        tableWidget->setObjectName(QString::fromUtf8("tableWidget"));
        tableWidget->setGeometry(QRect(40, 40, 651, 381));
        btn_SelectBossCancle = new QPushButton(page_4);
        btn_SelectBossCancle->setObjectName(QString::fromUtf8("btn_SelectBossCancle"));
        btn_SelectBossCancle->setGeometry(QRect(479, 459, 81, 21));
        label_7 = new QLabel(page_4);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(60, 430, 141, 51));
        label_7->setFont(font2);
        btn_SelectBossOk = new QPushButton(page_4);
        btn_SelectBossOk->setObjectName(QString::fromUtf8("btn_SelectBossOk"));
        btn_SelectBossOk->setGeometry(QRect(599, 459, 81, 21));
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QString::fromUtf8("page_5"));
        btn_H_BossIcon = new QPushButton(page_5);
        btn_H_BossIcon->setObjectName(QString::fromUtf8("btn_H_BossIcon"));
        btn_H_BossIcon->setGeometry(QRect(30, 80, 256, 100));
        btn_H_BossIcon->setMinimumSize(QSize(256, 100));
        btn_H_BossIcon->setMaximumSize(QSize(256, 100));
        btn_H_BossIcon->setIconSize(QSize(256, 100));
        lineEdit_H_BossName = new QLineEdit(page_5);
        lineEdit_H_BossName->setObjectName(QString::fromUtf8("lineEdit_H_BossName"));
        lineEdit_H_BossName->setGeometry(QRect(460, 80, 141, 21));
        lineEdit_H_BossName->setAutoFillBackground(false);
        lineEdit_H_BossName->setStyleSheet(QString::fromUtf8("background:rgba(255,0,0,0);"));
        label_8 = new QLabel(page_5);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(373, 80, 61, 21));
        label_8->setFont(font1);
        lineEdit_H_Score = new QLineEdit(page_5);
        lineEdit_H_Score->setObjectName(QString::fromUtf8("lineEdit_H_Score"));
        lineEdit_H_Score->setGeometry(QRect(460, 140, 141, 20));
        lineEdit_H_Score->setStyleSheet(QString::fromUtf8("background:rgba(255,0,0,0);"));
        label_9 = new QLabel(page_5);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(340, 140, 101, 20));
        label_9->setFont(font1);
        btn_H_CaptainIcon = new QPushButton(page_5);
        btn_H_CaptainIcon->setObjectName(QString::fromUtf8("btn_H_CaptainIcon"));
        btn_H_CaptainIcon->setGeometry(QRect(60, 280, 100, 100));
        btn_H_CaptainIcon->setMinimumSize(QSize(100, 100));
        btn_H_CaptainIcon->setMaximumSize(QSize(100, 100));
        btn_H_CaptainIcon->setIconSize(QSize(100, 100));
        btn_H_Valkyrie2Icon = new QPushButton(page_5);
        btn_H_Valkyrie2Icon->setObjectName(QString::fromUtf8("btn_H_Valkyrie2Icon"));
        btn_H_Valkyrie2Icon->setGeometry(QRect(180, 280, 100, 100));
        btn_H_Valkyrie2Icon->setMinimumSize(QSize(100, 100));
        btn_H_Valkyrie2Icon->setMaximumSize(QSize(100, 100));
        btn_H_Valkyrie2Icon->setIconSize(QSize(100, 100));
        btn_H_Valkyrie3Icon = new QPushButton(page_5);
        btn_H_Valkyrie3Icon->setObjectName(QString::fromUtf8("btn_H_Valkyrie3Icon"));
        btn_H_Valkyrie3Icon->setGeometry(QRect(300, 280, 100, 100));
        btn_H_Valkyrie3Icon->setMinimumSize(QSize(100, 100));
        btn_H_Valkyrie3Icon->setMaximumSize(QSize(100, 100));
        btn_H_Valkyrie3Icon->setIconSize(QSize(100, 100));
        btn_H_Cancle = new QPushButton(page_5);
        btn_H_Cancle->setObjectName(QString::fromUtf8("btn_H_Cancle"));
        btn_H_Cancle->setGeometry(QRect(509, 460, 81, 21));
        label_10 = new QLabel(page_5);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(60, 260, 54, 31));
        btn_H_Ok = new QPushButton(page_5);
        btn_H_Ok->setObjectName(QString::fromUtf8("btn_H_Ok"));
        btn_H_Ok->setGeometry(QRect(610, 460, 80, 21));
        lineEdit_H_Captain = new QLabel(page_5);
        lineEdit_H_Captain->setObjectName(QString::fromUtf8("lineEdit_H_Captain"));
        lineEdit_H_Captain->setGeometry(QRect(70, 390, 61, 21));
        lineEdit_H_Captain->setFont(font1);
        lineEdit_H_Valkyrie2 = new QLabel(page_5);
        lineEdit_H_Valkyrie2->setObjectName(QString::fromUtf8("lineEdit_H_Valkyrie2"));
        lineEdit_H_Valkyrie2->setGeometry(QRect(190, 390, 91, 21));
        lineEdit_H_Valkyrie2->setFont(font1);
        lineEdit_H_Valkyrie3 = new QLabel(page_5);
        lineEdit_H_Valkyrie3->setObjectName(QString::fromUtf8("lineEdit_H_Valkyrie3"));
        lineEdit_H_Valkyrie3->setGeometry(QRect(310, 390, 91, 21));
        lineEdit_H_Valkyrie3->setFont(font1);
        label_13 = new QLabel(page_5);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(60, 30, 101, 41));
        label_13->setFont(font2);
        icon2_4 = new QPushButton(page_5);
        icon2_4->setObjectName(QString::fromUtf8("icon2_4"));
        icon2_4->setGeometry(QRect(400, 10, 331, 501));
        icon2_4->setIconSize(QSize(306, 523));
        stackedWidget->addWidget(page_5);
        icon2_4->raise();
        btn_H_BossIcon->raise();
        lineEdit_H_BossName->raise();
        label_8->raise();
        lineEdit_H_Score->raise();
        label_9->raise();
        btn_H_CaptainIcon->raise();
        btn_H_Valkyrie2Icon->raise();
        btn_H_Valkyrie3Icon->raise();
        btn_H_Cancle->raise();
        label_10->raise();
        btn_H_Ok->raise();
        lineEdit_H_Captain->raise();
        lineEdit_H_Valkyrie2->raise();
        lineEdit_H_Valkyrie3->raise();
        label_13->raise();
        page_6 = new QWidget();
        page_6->setObjectName(QString::fromUtf8("page_6"));
        tableWidget_2 = new QTableWidget(page_6);
        tableWidget_2->setObjectName(QString::fromUtf8("tableWidget_2"));
        tableWidget_2->setGeometry(QRect(110, 70, 531, 401));
        btn_H_ValkyrieTavleWidgetCancle = new QPushButton(page_6);
        btn_H_ValkyrieTavleWidgetCancle->setObjectName(QString::fromUtf8("btn_H_ValkyrieTavleWidgetCancle"));
        btn_H_ValkyrieTavleWidgetCancle->setGeometry(QRect(510, 480, 80, 20));
        btn_H_ValkyrieTableWidegtOk = new QPushButton(page_6);
        btn_H_ValkyrieTableWidegtOk->setObjectName(QString::fromUtf8("btn_H_ValkyrieTableWidegtOk"));
        btn_H_ValkyrieTableWidegtOk->setGeometry(QRect(620, 480, 80, 20));
        stackedWidget->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName(QString::fromUtf8("page_7"));
        btn_H_upBoss = new QPushButton(page_7);
        btn_H_upBoss->setObjectName(QString::fromUtf8("btn_H_upBoss"));
        btn_H_upBoss->setGeometry(QRect(0, 60, 191, 111));
        btn_H_upBoss->setIconSize(QSize(256, 100));
        btn_H_2Boss = new QPushButton(page_7);
        btn_H_2Boss->setObjectName(QString::fromUtf8("btn_H_2Boss"));
        btn_H_2Boss->setGeometry(QRect(240, 60, 211, 111));
        btn_H_2Boss->setIconSize(QSize(256, 100));
        btn_H_3Boss = new QPushButton(page_7);
        btn_H_3Boss->setObjectName(QString::fromUtf8("btn_H_3Boss"));
        btn_H_3Boss->setGeometry(QRect(500, 60, 221, 111));
        btn_H_3Boss->setIconSize(QSize(256, 100));
        btn_HF_Cancle = new QPushButton(page_7);
        btn_HF_Cancle->setObjectName(QString::fromUtf8("btn_HF_Cancle"));
        btn_HF_Cancle->setGeometry(QRect(519, 470, 81, 21));
        btn_HF_Ok = new QPushButton(page_7);
        btn_HF_Ok->setObjectName(QString::fromUtf8("btn_HF_Ok"));
        btn_HF_Ok->setGeometry(QRect(629, 470, 81, 21));
        label_11 = new QLabel(page_7);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 40, 111, 21));
        QFont font3;
        font3.setPointSize(15);
        label_11->setFont(font3);
        label_upboss = new QLabel(page_7);
        label_upboss->setObjectName(QString::fromUtf8("label_upboss"));
        label_upboss->setGeometry(QRect(40, 180, 121, 20));
        label_upboss->setFont(font1);
        label_2boss = new QLabel(page_7);
        label_2boss->setObjectName(QString::fromUtf8("label_2boss"));
        label_2boss->setGeometry(QRect(290, 180, 121, 20));
        label_2boss->setFont(font1);
        label_3boss = new QLabel(page_7);
        label_3boss->setObjectName(QString::fromUtf8("label_3boss"));
        label_3boss->setGeometry(QRect(550, 180, 111, 21));
        label_3boss->setFont(font1);
        label_12 = new QLabel(page_7);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 10, 81, 41));
        label_12->setFont(font3);
        textEdit = new QTextEdit(page_7);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setGeometry(QRect(260, 350, 191, 101));
        QFont font4;
        font4.setFamily(QString::fromUtf8("\346\245\267\344\275\223"));
        textEdit->setFont(font4);
        btn_HF_upBoss_1 = new QPushButton(page_7);
        btn_HF_upBoss_1->setObjectName(QString::fromUtf8("btn_HF_upBoss_1"));
        btn_HF_upBoss_1->setGeometry(QRect(0, 270, 51, 71));
        btn_HF_upBoss_1->setIconSize(QSize(100, 100));
        btn_HF_upBoss_2 = new QPushButton(page_7);
        btn_HF_upBoss_2->setObjectName(QString::fromUtf8("btn_HF_upBoss_2"));
        btn_HF_upBoss_2->setGeometry(QRect(70, 270, 51, 71));
        btn_HF_upBoss_2->setIconSize(QSize(100, 100));
        btn_HF_upBoss_3 = new QPushButton(page_7);
        btn_HF_upBoss_3->setObjectName(QString::fromUtf8("btn_HF_upBoss_3"));
        btn_HF_upBoss_3->setGeometry(QRect(140, 270, 51, 71));
        btn_HF_upBoss_3->setIconSize(QSize(100, 100));
        btn_HF_2Boss_1 = new QPushButton(page_7);
        btn_HF_2Boss_1->setObjectName(QString::fromUtf8("btn_HF_2Boss_1"));
        btn_HF_2Boss_1->setGeometry(QRect(240, 270, 51, 71));
        btn_HF_2Boss_1->setIconSize(QSize(100, 100));
        btn_HF_2Boss_3 = new QPushButton(page_7);
        btn_HF_2Boss_3->setObjectName(QString::fromUtf8("btn_HF_2Boss_3"));
        btn_HF_2Boss_3->setGeometry(QRect(400, 270, 51, 71));
        btn_HF_2Boss_3->setIconSize(QSize(100, 100));
        btn_HF_2Boss_2 = new QPushButton(page_7);
        btn_HF_2Boss_2->setObjectName(QString::fromUtf8("btn_HF_2Boss_2"));
        btn_HF_2Boss_2->setGeometry(QRect(320, 270, 51, 71));
        btn_HF_2Boss_2->setIconSize(QSize(100, 100));
        btn_HF_3Boss_1 = new QPushButton(page_7);
        btn_HF_3Boss_1->setObjectName(QString::fromUtf8("btn_HF_3Boss_1"));
        btn_HF_3Boss_1->setGeometry(QRect(500, 270, 51, 71));
        btn_HF_3Boss_1->setIconSize(QSize(100, 100));
        btn_HF_3Boss_2 = new QPushButton(page_7);
        btn_HF_3Boss_2->setObjectName(QString::fromUtf8("btn_HF_3Boss_2"));
        btn_HF_3Boss_2->setGeometry(QRect(590, 270, 51, 71));
        btn_HF_3Boss_2->setIconSize(QSize(100, 100));
        btn_HF_3Boss_3 = new QPushButton(page_7);
        btn_HF_3Boss_3->setObjectName(QString::fromUtf8("btn_HF_3Boss_3"));
        btn_HF_3Boss_3->setGeometry(QRect(670, 270, 51, 71));
        btn_HF_3Boss_3->setIconSize(QSize(100, 100));
        stackedWidget->addWidget(page_7);
        page_8 = new QWidget();
        page_8->setObjectName(QString::fromUtf8("page_8"));
        treeWidget = new QTreeWidget(page_8);
        QTreeWidgetItem *__qtreewidgetitem = new QTreeWidgetItem();
        __qtreewidgetitem->setText(0, QString::fromUtf8("1"));
        treeWidget->setHeaderItem(__qtreewidgetitem);
        treeWidget->setObjectName(QString::fromUtf8("treeWidget"));
        treeWidget->setGeometry(QRect(10, 10, 621, 481));
        btn_RH_back = new QPushButton(page_8);
        btn_RH_back->setObjectName(QString::fromUtf8("btn_RH_back"));
        btn_RH_back->setGeometry(QRect(640, 459, 80, 31));
        btn_RH_ok = new QPushButton(page_8);
        btn_RH_ok->setObjectName(QString::fromUtf8("btn_RH_ok"));
        btn_RH_ok->setGeometry(QRect(640, 410, 80, 31));
        btn_RH_delete = new QPushButton(page_8);
        btn_RH_delete->setObjectName(QString::fromUtf8("btn_RH_delete"));
        btn_RH_delete->setGeometry(QRect(640, 30, 80, 31));
        stackedWidget->addWidget(page_8);

        horizontalLayout->addWidget(stackedWidget);


        retranslateUi(Widget);

        stackedWidget->setCurrentIndex(7);


        QMetaObject::connectSlotsByName(Widget);
    } // setupUi

    void retranslateUi(QWidget *Widget)
    {
        Widget->setWindowTitle(QApplication::translate("Widget", "Widget", nullptr));
        btn_FoundHomework->setText(QApplication::translate("Widget", "\346\237\245\344\275\234\344\270\232", nullptr));
        btn_Valkyrie->setText(QApplication::translate("Widget", "\345\245\263\346\255\246\347\245\236\345\275\225\345\205\245", nullptr));
        btn_SetBoss->setText(QApplication::translate("Widget", "boos\345\275\225\345\205\245", nullptr));
        btn_SetHomework->setText(QApplication::translate("Widget", "\344\275\234\344\270\232\345\275\225\345\205\245", nullptr));
        icon2->setText(QString());
        icontext->setText(QString());
        btn_ResetHomework->setText(QApplication::translate("Widget", "\344\275\234\344\270\232\344\277\256\346\224\271", nullptr));
        label_3->setText(QApplication::translate("Widget", "\345\245\263\346\255\246\347\245\236\345\244\264\345\203\217", nullptr));
        label->setText(QApplication::translate("Widget", "\345\245\263\346\255\246\347\245\236\345\220\215\345\255\227", nullptr));
        label_2->setText(QApplication::translate("Widget", "\345\245\263\346\255\246\347\245\236\346\230\265\347\247\260", nullptr));
#ifndef QT_NO_WHATSTHIS
        btn_ValkyrieIcon->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        btn_ValkyrieIcon->setText(QString());
        btn_ValkyrieOk->setText(QApplication::translate("Widget", "\347\241\256\345\256\232", nullptr));
        btn_ValkyrieCancel->setText(QApplication::translate("Widget", "\345\217\226\346\266\210", nullptr));
        label_15->setText(QApplication::translate("Widget", "\345\245\263\346\255\246\347\245\236\345\275\225\345\205\245", nullptr));
        icon2_3->setText(QString());
        btn_BossOk->setText(QApplication::translate("Widget", "\347\241\256\345\256\232", nullptr));
        btn_BossCancle->setText(QApplication::translate("Widget", "\345\217\226\346\266\210", nullptr));
        label_4->setText(QApplication::translate("Widget", "Boss\345\220\215\347\247\260", nullptr));
        label_5->setText(QApplication::translate("Widget", "Boss\346\230\265\347\247\260", nullptr));
        label_6->setText(QApplication::translate("Widget", "Boss\345\233\276\347\211\207", nullptr));
        btn_BossIcon->setText(QString());
        label_14->setText(QApplication::translate("Widget", "BOSS\345\275\225\345\205\245", nullptr));
        icon2_2->setText(QString());
        btn_SelectBossCancle->setText(QApplication::translate("Widget", "\345\217\226\346\266\210", nullptr));
        label_7->setText(QApplication::translate("Widget", "\351\200\211\346\213\251boss", nullptr));
        btn_SelectBossOk->setText(QApplication::translate("Widget", "\347\241\256\345\256\232", nullptr));
        btn_H_BossIcon->setText(QString());
        label_8->setText(QApplication::translate("Widget", "Boss\345\220\215", nullptr));
        label_9->setText(QApplication::translate("Widget", "\345\210\206\346\225\260\357\274\210\351\235\236up\357\274\211", nullptr));
        btn_H_CaptainIcon->setText(QString());
        btn_H_Valkyrie2Icon->setText(QString());
        btn_H_Valkyrie3Icon->setText(QString());
        btn_H_Cancle->setText(QApplication::translate("Widget", "\345\217\226\346\266\210", nullptr));
        label_10->setText(QApplication::translate("Widget", "\351\230\237\351\225\277", nullptr));
        btn_H_Ok->setText(QApplication::translate("Widget", "\347\241\256\345\256\232", nullptr));
        lineEdit_H_Captain->setText(QApplication::translate("Widget", "\351\230\237\351\225\277", nullptr));
        lineEdit_H_Valkyrie2->setText(QApplication::translate("Widget", "2\345\217\267\345\245\263\346\255\246\347\245\236", nullptr));
        lineEdit_H_Valkyrie3->setText(QApplication::translate("Widget", "3\345\217\267\345\245\263\346\255\246\347\245\236", nullptr));
        label_13->setText(QApplication::translate("Widget", "\344\275\234\344\270\232\345\275\225\345\205\245", nullptr));
        icon2_4->setText(QString());
        btn_H_ValkyrieTavleWidgetCancle->setText(QApplication::translate("Widget", "\345\217\226\346\266\210", nullptr));
        btn_H_ValkyrieTableWidegtOk->setText(QApplication::translate("Widget", "\347\241\256\345\256\232", nullptr));
        btn_H_upBoss->setText(QString());
        btn_H_2Boss->setText(QString());
        btn_H_3Boss->setText(QString());
        btn_HF_Cancle->setText(QApplication::translate("Widget", "\345\217\226\346\266\210", nullptr));
        btn_HF_Ok->setText(QApplication::translate("Widget", "\347\241\256\345\256\232", nullptr));
        label_11->setText(QApplication::translate("Widget", "up boss", nullptr));
        label_upboss->setText(QApplication::translate("Widget", "upBoss", nullptr));
        label_2boss->setText(QApplication::translate("Widget", "2Boss", nullptr));
        label_3boss->setText(QApplication::translate("Widget", "3Boss", nullptr));
        label_12->setText(QApplication::translate("Widget", "\346\237\245\344\275\234\344\270\232", nullptr));
        btn_HF_upBoss_1->setText(QString());
        btn_HF_upBoss_2->setText(QString());
        btn_HF_upBoss_3->setText(QString());
        btn_HF_2Boss_1->setText(QString());
        btn_HF_2Boss_3->setText(QString());
        btn_HF_2Boss_2->setText(QString());
        btn_HF_3Boss_1->setText(QString());
        btn_HF_3Boss_2->setText(QString());
        btn_HF_3Boss_3->setText(QString());
        btn_RH_back->setText(QApplication::translate("Widget", "\345\217\226\346\266\210", nullptr));
        btn_RH_ok->setText(QApplication::translate("Widget", "\344\277\235\345\255\230", nullptr));
        btn_RH_delete->setText(QApplication::translate("Widget", "\345\210\240\351\231\244", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Widget: public Ui_Widget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WIDGET_H
